### ISSUE TITLE
Conceal links

### ISSUE THREAD

**Issue by tonyspiff** [habamax/vim-asciidoctor#47] opened 2020-01-19 19:33 UTC
It would be very nice to have the ability to hide URLs on links with labels as many markdown plugins do under a `conceallevel`.

**Comment by habamax** [comment] 2020-01-20 06:06
@mg979 has implemented conceal for bold/italic/code. I believe links are a good thing to include.

Should we also conceal inner links like `<<Section name>>` or `<<anchor name, link description>>`?

**Comment by habamax** [comment] 2020-01-20 06:57
@tonyspiff please test (I myself don't use conceal very much)

![asciidoctor-conceal-links](https://user-images.githubusercontent.com/234774/72704946-2403f500-3b6b-11ea-85d5-7302fd380343.gif)

**Comment by habamax** [comment] 2020-01-20 14:58
Hmm, not sure what to do with `image::dq-framework-int-arch.svg[]`

This kind of links are completely invisible for conceallevel=3

**Comment by habamax** [comment] 2020-01-20 14:59
@mg979 do you have any idea?

**Comment by tonyspiff** [comment] 2020-01-20 16:37
I tested with a few examples from the AsciiDoc quick syntax and it's failing with these naked URIs (no explicit `link` attribute):
```
https://asciidoctor.org[Asciidoctor]
https://github.com/asciidoctor[Asciidoctor @ *GitHub*]
````
And also strange behaviour on link detection and concealment on these:
```
link:++https://example.org/?q=[a b]++[URL with special characters]
https://asciidoctor.org - automatic!
```

**Comment by mg979** [comment] 2020-01-20 18:35
@habamax maybe this?
```vim
syn region asciidoctorUrl        matchgroup=Conceal start="\%(link\|xref\|image\)::\?.*\[\ze[^]]" end="\]" concealends oneline keepend skipwhite
```
that is:
- make greedy the search for `[` so that it always looks for the last one, fixing:
```
    link:++https://example.org/?q=[a b]++[URL with special characters]
```
- ensure that there is at least one character between the brackets

@tonyspiff 
> I tested with a few examples from the AsciiDoc quick syntax and it's failing with these naked URIs (no explicit link attribute):

    https://asciidoctor.org[Asciidoctor]
    https://github.com/asciidoctor[Asciidoctor @ *GitHub*]

I don't think it's a good idea to conceal those because if the URL contains brackets with that pattern, it would be wrongly displayed, so I'd use `link::` if I want to conceal it. It's also a way to have non-concealed links if one wants them.

**Comment by habamax** [comment] 2020-01-20 18:54
> @habamax maybe this?

Looks like it is! I would also add:

```
	syn region asciidoctorUrl        matchgroup=Conceal start="\%(link\|xref\|image\)::\?" end="\[\]" concealends oneline keepend skipwhite
```
to highlight link::http://link.com[] as link.

![asciidoctor-conceal-links2](https://user-images.githubusercontent.com/234774/72750901-2dbf4400-3bcf-11ea-8e46-dbed4fa1c6ec.gif)




> I don't think it's a good idea to conceal those because if the URL contains brackets with that pattern, it would be wrongly displayed, so I'd use `link::` if I want to conceal it. It's also a way to have non-concealed links if one wants them.

Probably you're right, it would be tricky.

BTW, should we highlight as links barebone urls? `http://google.com/...` ?

**Comment by habamax** [comment] 2020-01-20 19:10
current url examples:

```
== Section 1

* [x] link::https://hello_world.com[link description]
* [x] now there is a link without description to <<Section 1>>
* [x] now there is a link with description to <<Section 1, hello world>>
* [x] link:++https://example.org/?q=[a b]++[URL with special characters]
 
* [x] Space in image description image::http://dq-framework-int-arch.svg[  ]
* [x] Not sure if this should be concealed image::http://dq-framework-int-arch.svg[]
* [x] Not sure if this should be concealed link::dq-framework-int-arch.svg[]

* [ ] https://asciidoctor.org - automatic! Currently no automatic links (no matter concealed or not)
* [ ] What to do with this? https://asciidoctor.org[Asciidoctor]
* [ ] What to do with this? https://github.com/asciidoctor[Asciidoctor @ *GitHub*]

```

**Comment by habamax** [comment] 2020-01-20 19:36
@mg979 , @tonyspiff could you pls check latest master?

**Comment by mg979** [comment] 2020-01-20 20:44
```vim
	syn region asciidoctorUrl        matchgroup=Conceal start="\%(link\|xref\|image\)::\?.*\[\ze[^]]" end="\]" concealends oneline keepend skipwhite
	syn match asciidoctorUrlDescription "\[.\{-}\]" contained containedin=asciidoctorUrl
	syn match asciidoctorUrl "\%(http\|ftp\)s\?://\S\+\ze\%(\[.\{-}\]\)" nextgroup=asciidoctorUrlDescription
	syn region asciidoctorUrl        matchgroup=Conceal start="\%(link\|xref\|image\)::\?" end="\[\s*\]" concealends oneline keepend skipwhite
```

Line 4 is new, what does it do that line 1 doesn't? I say it because this highlight group is already the slowest one, so now there's two of them.

**Comment by habamax** [comment] 2020-01-21 03:22
> Edit: ok I see it's for the ones in the middle (`'not sure if...`). Personally I would not do it, it makes syntax slower for no benefit. If one leaves the description empty, it's at most as a reminder for something that must be filled, and in that case it's better not to conceal it at all. My opinion.

Well, I can see your point, so all of them shouldn't be concealed, right?

```
* [x] Space in image description image::http://dq-framework-int-arch.svg[  ]
* [x] Not sure if this should be concealed image::http://dq-framework-int-arch.svg[]
* [x] Not sure if this should be concealed link::dq-framework-int-arch.svg[]
```

But probably still showed as links? Like non-concealed version does?

**Comment by habamax** [comment] 2020-01-21 03:28
@mg979 if I remove this line, there is an issue with
```
* [x] Space in image description image::http://dq-framework-int-arch.svg[  ]
```

![asciidoctor-conceal-links3](https://user-images.githubusercontent.com/234774/72773101-258af700-3c17-11ea-9bae-661fcbca634b.gif)

**Comment by habamax** [comment] 2020-01-21 03:55
Ok, with https://github.com/habamax/vim-asciidoctor/commit/07cdcd4599b15bafc5d5ea2ed8ea860e4b127eba we don't conceal "empty" `link/image::` but highlight it as links.


![image](https://user-images.githubusercontent.com/234774/72774263-f70f1b00-3c1a-11ea-90b3-bcb0ce1cba9d.png)

**Comment by mg979** [comment] 2020-01-21 07:24
For `performance` I meant the results give by `syntime report`, also with the last commit the slowest pattern is doubled up.
```
  0.102918   10784  0       0.002019    0.000010  asciidoctorUrl     \%(link\|xref\|image\)::\?
  0.095717   10784  0       0.000115    0.000009  asciidoctorUrl     \%(link\|xref\|image\)::\?.*\[\ze[^]]
  0.092578   11116  332     0.000328    0.000008  asciidoctorCode    \m\%(^\|[[:punct:][:space:]]\@<=\)`\ze[^` ].\{-}\S
  0.091132   10784  0       0.000156    0.000008  asciidoctorBoldItalic \m\%(^\|[[:punct:][:space:]]\@<=\)\*_\ze[^*_ ].\{-}\S
  0.084758   11143  359     0.000488    0.000008  asciidoctorItalic  \m\%(^\|[[:punct:][:space:]]\@<=\)_\ze[^_ ].\{-}\S
  0.082547   10900  116     0.000180    0.000008  asciidoctorBold    \m\%(^\|[[:punct:][:space:]]\@<=\)\*\ze[^* ].\{-}\S
  0.071579   10784  0       0.000102    0.000007  asciidoctorUrl     \%(http\|ftp\)s\?://\S\+\ze\%(\[.\{-}\]\)
  0.067461   10784  0       0.000237    0.000006  asciidoctorDefList .\{-}::\_s\%(\_^\n\)\?
```

If you take commit 9f5138e and remove https://github.com/habamax/vim-asciidoctor/blob/9f5138e7048a97c2325b24a61bf00da3fd78fe4e/syntax/asciidoctor.vim#L73 it looks exactly the same as in the last commit, but there's no wasted syntax pattern.

**Comment by habamax** [comment] 2020-01-21 07:33
@mg979 so do you mean that highlighting url as link -- `link::http://google.com[]` is not needed for concealed version of syntax?

Don't get me wrong -- I don't use conceal, so here I will trust you, the one who came out with all conceal stuff here :)

**Comment by habamax** [comment] 2020-01-21 08:47
@mg979 I have removed line in question but updated your regexes in:

	syn region asciidoctorUrl        matchgroup=Conceal start="\%(link\|xref\|image\)::\?\(.*\[\ze[^]]\)\?" end="\]\|\[]" concealends oneline keepend skipwhite

To be able to conceal `link::` and `[]` parts if description is not there:

* link::hello_world.svg[] should be properly concealed
* I have also checked performance with syntime report -- it has been slightly faster before but not critically.

Could you pls check?

**Comment by mg979** [comment] 2020-01-21 15:52
This is the best I could do (commit here 5ea14358f32d36eb62b1639266feda4f5f14e958). Given the test file
```

== Section 1

* [x] link::https://hello_world.com[one colon too many]
* [x] link:https://hello_world.com[Link description]
* [x] now there is a link without description to <<Section 1>>
* [x] now there is a link with description to <<Section 1, hello world>>
* [x] link:++https://example.org/?q=[a b]++[URL with special characters]
 
* [x] Space in image description image::http://dq-framework-int-arch.svg[  ]
* [x] Description can't be empty or contain just spaces image::http://dq-framework-int-arch.svg[ char ]
* [x] This is an invalid link and should't be concealed: image::http://dq-framework-int-arch.svg[]
* [x] This is an invalid link and should't be concealed: link:dq-framework-int-arch.svg[]

* [ ] https://asciidoctor.org - automatic!
* [ ] What to do with this? https://asciidoctor.org[Asciidoctor]
* [ ] What to do with this? https://github.com/asciidoctor[Asciidoctor @ *GitHub*]
```

that results in

![Imgur](https://i.imgur.com/dsYQ2pU.jpg)

In vim with conceal:

![Imgur](https://i.imgur.com/JtA22dZ.jpg)

Without conceal:

![Imgur](https://i.imgur.com/XWsqeFm.jpg)

Note that the first line (with `link::`) looks strange because `link` must be followed by on colon, not two. I couldn't do better than this.

**Comment by habamax** [comment] 2020-01-21 16:10
Thx @mg979!

On non-concealed version I can see `<<...>>` highlighted differently?
Also why image links are invalid? Would the be invalid if there was no `http://`?

**Comment by tonyspiff** [comment] 2020-01-21 16:13
> ```
> https://asciidoctor.org[Asciidoctor]
> https://github.com/asciidoctor[Asciidoctor @ *GitHub*]
> ```
> 
> I don't think it's a good idea to conceal those because if the URL contains brackets with that pattern, it would be wrongly displayed, so I'd use `link::` if I want to conceal it. It's also a way to have non-concealed links if one wants them.

It might be harder to implement correctly but I fail to see how concealing these naked links is a bad idea. Also it's rare to have a bracket in a URI - and they could be properly coded as `%5B` and `%5D`.

**Comment by habamax** [comment] 2020-01-21 16:18
> Also it's rare to have a bracket in a URI - and they could be properly coded as `%5B` and `%5D`.

Actually it was in your example:
```
* [x] link:++https://example.org/?q=[a b]++[URL with special characters]
```

**Comment by tonyspiff** [comment] 2020-01-21 17:15
> > Also it's rare to have a bracket in a URI - and they could be properly coded as `%5B` and `%5D`.
> 
> Actually it was in your example:
> 
> ```
> * [x] link:++https://example.org/?q=[a b]++[URL with special characters]
> ```

I know. Rare nonetheless. But my point is given the choice between having either concealed naked links or properly parsed URIs with brackets I'd pick the former.

**Comment by habamax** [comment] 2020-01-21 17:28
> I know. Rare nonetheless. But my point is given the choice between having either concealed naked links or properly parsed URIs with brackets I'd pick the former.

Have a look into the screenshots provided by @mg979 -- it is there, naked link ishighlighted and `https://url.com[]` is concealed.

So we are trying to figure out how to do it, which turned out as not that easy task.

**Comment by mg979** [comment] 2020-01-21 18:14
@tonyspiff the naked links are done already, you can see them in the picture.

@habamax I made a mistake, that when links/images/videos have empty bracket should fallback to the non-concealed highlight, because they are not invalid as I thought. The last `link` in the second section is clickable, even if it has no description, and images/videos don't need a description.

So i have to add `video` and use a fallback for non-concealed links.

**Comment by habamax** [comment] 2020-01-21 18:25
@mg979 I had a fallback to non-concealed url in one of my prev commits which was slow :)

**Comment by mg979** [comment] 2020-01-21 18:28
@habamax no problem, now I'm actually doing them as partially concealed (just the part before the colon), and they are all contained so performance is not a problem.

**Comment by habamax** [comment] 2020-01-21 18:28
> @habamax no problem, now I'm actually doing them as partially concealed (just the part before the colon), and they are all contained so performance is not a problem.

Nice!

**Comment by mg979** [comment] 2020-01-21 19:04
There are two alternatives:

- images behave like links and don't show address if name is defined
![Imgur](https://i.imgur.com/YfWAVny.jpg)

- images always show address and name/options, differently from links:
![Imgur](https://i.imgur.com/AC0Y0Lz.jpg)

**Comment by habamax** [comment] 2020-01-21 19:07
> There are two alternatives:

I don't have preference here.

**Comment by habamax** [comment] 2020-01-21 19:10
@mg979 check this out:
![image](https://user-images.githubusercontent.com/234774/72834956-e30afe00-3c9a-11ea-8c0a-d3e56d23934e.png)

**Comment by mg979** [comment] 2020-01-21 19:12
Which commit? I can't see it.

**Comment by habamax** [comment] 2020-01-21 19:17
> Which commit? I can't see it.

I have just grabbed your file and test it. Didn't put into repo yet.

The issue is that you use PreProc for asciidoctorAnchor and asciidoctorLink as far as I can see

**Comment by habamax** [comment] 2020-01-21 19:21
Another issue with blocks that use `contains=CONTAINED`:

![image](https://user-images.githubusercontent.com/234774/72835766-5e20e400-3c9c-11ea-85ff-fc249760a067.png)

**Comment by mg979** [comment] 2020-01-21 19:28
That `File` pattern is very unspecific, can you make a gist with a complete test file (all sorts of stuff)? I will do it tomorrow (too sleepy now).

**Comment by habamax** [comment] 2020-01-21 19:28
I have pushed your version + update to highlight and fix to source/literal blocks, pls check @mg979

**Comment by mg979** [comment] 2020-01-21 19:30
Tomorrow I'll test stuff better, also I think version 1 is better (more conceal), and maybe we can have a command to toggle conceal.

**Comment by habamax** [comment] 2020-01-21 19:31
> That `File` pattern is very unspecific, can you make a gist with a complete test file (all sorts of stuff)? I will do it tomorrow (too sleepy now).

It is unspecific but it is `containded`. In vim there is `contains=CONTAINED` for a region and it means include all syntax elements that has `contained` property. You can add exceptions to it with commas, like `contains=CONTAINED,asciidoctorFile,...`. It means that it should contain all contained elements but asciidoctorFile.

**Comment by habamax** [comment] 2020-01-21 19:36
> Tomorrow I'll test stuff better, also I think version 1 is better (more conceal), and maybe we can have a command to toggle conceal.

Thx for your help, @mg979! I am not sure about command to toggle conceal, it would be better and easier for future us to have a single conceal version.

If you like the other one we can test it and have it instead of current.

**Comment by habamax** [comment] 2020-01-21 19:40
> can you make a gist with a complete test file (all sorts of stuff)? I will do it tomorrow (too sleepy now).

https://gist.github.com/habamax/bd90eb4ddf150571d7d197bee501bdfd

**Comment by habamax** [comment] 2020-01-22 06:18
Hi @tonyspiff,

Could you pls check the latest version?

**Comment by tonyspiff** [comment] 2020-01-22 08:23
This one is missing the underline on `.org`:
```
devel@discuss.arquillian.org
```

BTW, if you want to support links with attributes (Asciidoctor only) then these are not correct:
```
https://discuss.asciidoctor.org[Discuss Asciidoctor,role=external,window=_blank]
https://discuss.asciidoctor.org[Discuss Asciidoctor^]
https://example.org["Google, Yahoo, Bing^",role=teal]
```
...as they should conceal to:
```
[Discuss Asciidoctor]
[Discuss Asciidoctor]
[Google, Yahoo, Bing]
```

And it used to support empty links as in:
```
link:[hello]
```
Now it doesn't but I'm not sure this is a valid syntax

**Comment by habamax** [comment] 2020-01-22 08:39
> This one is missing the underline on `.org`:

indeed.



> BTW, if you want to support links with attributes (Asciidoctor only) then these are not correct:

This one is hard -- not sure I would be able to handle it.  Will try of course :)



> Now it doesn't but I'm not sure this is a valid syntax

Me too.

**Comment by mg979** [comment] 2020-01-22 09:24
> This one is missing the underline on .org:

This was a bug, fix is in https://github.com/habamax/vim-asciidoctor/pull/49/commits/58a6488bbc2242c1a0b0858104dd887bb018a214

> BTW, if you want to support links with attributes (Asciidoctor only) then these are not correct

I tried to implement that in https://github.com/habamax/vim-asciidoctor/pull/49/commits/b449b67c347d2394f2bfc86ae493ebe2a0905a50, but probably it won't work for everything.
It also conceals all attributes, not just their value. I think doing more than this would be extremely complicated, if possible at all (I won't even try).

You'll need to set two options:

    let g:asciidoctor_conceal_attributes = 1
    let g:asciidoctor_compact_media_links = 1

**Comment by habamax** [comment] 2020-01-22 10:15
> I tried to implement that in [b449b67](https://github.com/habamax/vim-asciidoctor/commit/b449b67c347d2394f2bfc86ae493ebe2a0905a50), but probably it won't work for everything.
> It also conceals all attributes, not just their value. I think doing more than this would be extremely complicated, if possible at all (I won't even try).

* It doesn't work for `^` at the end
* It doesn't take into consideration `"description, in a quotes"`

I guess we have to stop somewhere.

Should we keep this `conceal_attributes` or just note in README that it doesn't conceal them?

**Comment by mg979** [comment] 2020-01-22 11:35
@habamax 
This kind of things leads to endless corner cases... I made my attempt, if it's not good enough it's better to drop it.

**Comment by habamax** [comment] 2020-01-22 11:38
> @habamax
> This kind of things leads to endless corner cases... I made my attempt, if it's not good enough it's better to drop it.

Then I will add a note to readme regarding link conceal limitations and drop it.

**Closed** 2020-01-22 12:17 UTC
Labels: enhancement

**Comment by tonyspiff** [comment] 2020-01-22 16:18
@habamax 
I found another issue: if `concealcursor` is on (if you're not familiar, it would conceal the line where the cursor is on) you can't motion (w, b, h, l, etc.) over the concealed text properly.

**Comment by habamax** [comment] 2020-01-22 16:36
I have to read about it in vimhelp :)

**Comment by habamax** [comment] 2020-01-22 16:40
@tonyspiff I believe this kind of issue is for all syntaxes that use conceal.

also, note the help:

	Keep in mind that the cursor position is not always where it's
	displayed.  E.g., when moving vertically it may change column.

It actually moves cursor but it is concealed -- try to press several times `w` for example it "stops" (because it moves through concealed text) and then continues as soon as it passed hidden part.

I might be wrong though.

**Comment by habamax** [comment] 2020-01-22 16:56
@tonyspiff check this:

![vim-asciidoctor-conceal](https://user-images.githubusercontent.com/234774/72915408-4c4d4880-3d51-11ea-8a16-d850ad82850d.gif)

**Comment by tonyspiff** [comment] 2020-01-22 17:36
> @tonyspiff I believe this kind of issue is for all syntaxes that use conceal.

I don't think so. [This markdown extension](https://github.com/plasticboy/vim-markdown) for instance implements conceal navigation as I would expect.

**Comment by habamax** [comment] 2020-01-22 17:47
What is you concealcursor settings?

**Comment by habamax** [comment] 2020-01-22 17:53
With builtin markdown (the one from tpope) I experience the same behaviour.

Let me check your link

**Comment by habamax** [comment] 2020-01-22 18:02
I feel dumb... How do you use it? Built in markdown takes precedence over it.

**Comment by habamax** [comment] 2020-01-22 18:08
![vim-asciidoctor-conceal2](https://user-images.githubusercontent.com/234774/72920884-452b3800-3d5b-11ea-820a-a51827416ecb.gif)

**Comment by tonyspiff** [comment] 2020-01-29 16:09
I suppose they have similar behaviour. It's just down to the fact that markdown has trailing URIs. AsciiDoc's leading URI means that you have to motion through it while invisible until you get to the actual label.

Another thing I noticed is netrw's `gx` (to open the URIs on their associated default app) doesn't work if the cursor is on the label - only on the link itself. Is that intended? If not, maybe I should open a separate issue as this happens regardless of the `conceallevel`.

**Comment by habamax** [comment] 2020-01-29 16:21
> I suppose they have similar behaviour. It's just down to the fact that markdown has trailing URIs. AsciiDoc's leading URI means that you have to motion through it while invisible until you get to the actual label.

Indeed, that is the case.



> Another thing I noticed is netrw's `gx` (to open the URIs on their associated default app) doesn't work if the cursor is on the label - only on the link itself. Is that intended? If not, maybe I should open a separate issue as this happens regardless of the `conceallevel`.

Please do a separate issue. I will have to enable netrw back though :)

**Comment by habamax** [comment] 2020-01-29 16:34
> Another thing I noticed is netrw's `gx` (to open the URIs on their associated default app) doesn't work if the cursor is on the label - only on the link itself. Is that intended? If not, maybe I should open a separate issue as this happens regardless of the `conceallevel`.

Actually I don't think it would be possible to do it reliably.
For markdown it is the same thing -- put your cursor on a label `[hello world](http://www.url.com)` (not concealed) and press `gx`.

Or am I miss something?

**Comment by habamax** [comment] 2020-01-29 16:38
> Or am I miss something?

Indeed. You were speaking about not built-in markdown extension and it remaps `gx`
